name: Daily Commit

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write   # <-- allows pushing commits

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file with timestamp (23f1001647@ds.study.iitm.ac.in)
        run: |
          echo "Last updated: $(date -u)" > last_update.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "23f1001647@ds.study.iitm.ac.in"
          git add last_update.txt
          git commit -m "Automated commit at $(date -u)" || echo "No changes to commit"
          git push
